session_config:
    n_inter_threads: 2
    n_intra_threads: 32

data_config:
    path: /global/cscratch1/sd/sfarrell/atlas-rpv-images
    n_train: 1024 #64000
    n_valid: 1024 #32000
    n_test: 1024 #32000

model_config:
    conv_sizes: [16, 32, 64]
    fc_sizes: [128]
    optimizer: Adam
    lr: 0.001
    dropout: 0.2

training_config:
    batch_size: 128
    epochs: 4
