session_config:
    n_inter_threads: 2
    n_intra_threads: 32

data_config:
    path: /global/cscratch1/sd/sfarrell/atlas-rpv-images
    n_train: 64000 #412416
    n_valid: 32000
    n_test: 32000

model_config:
    conv_sizes: [16, 32, 64]
    fc_sizes: [128]
    optimizer: Adam
    learning_rate: 0.001
    scale_learning_rate: true
    dropout: 0.2

training_config:
    batch_size: 128
    batch_size_per_node: true
    epochs: 4

checkpoint_file: $SCRATCH/ml4sci-tutorial/checkpoints/model.h5
